version: 2
jobs:
  build-creeper:
    docker:
      - image: oluwafemisule/scala

    working_directory: ~/political-sentiment/creeper/src

    steps:
      - checkout

      - run:
          name: "Run tests"
          command: sbt test
      - run:
          name: "Build jar"
          command: "sbt assembly"
  deploy-creeper:
    docker:
      - image: oluwafemisule/scala
    working_directory: ~/political-sentiment/creeper/src
    steps:
      - run:
          name: Deploy if tests pass to AWS
          command: echo "TODO"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-creeper
      - deploy-creeper:
          requires:
            - build-creeper
          filters:
            branches:
              only: 
                - master
                - /lambda-*/