creeper-defaults: &creeper-defaults
  working_directory: ~/political-sentiment
  docker:
    - image: oluwafemisule/scala:2.12.6

version: 2
jobs:
  build-creeper:
    <<: *creeper-defaults
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: cd creeper && sbt test
      - run:
          name: "Build jar"
          command: cd creeper && sbt assembly
  deploy-creeper:
    <<: *creeper-defaults
    steps:
      - run: 
          name: Update package source list
          command: echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" > /etc/apt/sources.list
      - run: 
          name: Install AWS CLI
          command: apt-get update && apt-get install -y python3-pip && pip3 install awscli
      - run:
          name: Deploy to AWS
          command: ./bin/upload-function creeper creeper/target/scala-2.12/creeper.jar

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-creeper
      - deploy-creeper:
          requires:
            - build-creeper
          filters:
            branches:
              only: 
                - master
                - /lambda-*/
